

//   Supabase API
export const supabaseUrl = 'https://mdzeadcxtnqlysicirsb.supabase.co';
export const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kemVhZGN4dG5xbHlzaWNpcnNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMxMzQyMzAsImV4cCI6MjA0ODcxMDIzMH0.csrPTlKYdBGKYeEcfFxKpl5xNeLC4Wpxomy4jQaunMw';